name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Well Its your first issue follow contributing guidlines'
        pr-message: 'Great! :Heart:, plases follow the contributing guidlines, and Happy Coding '
